#Build Environment
# Image node js
FROM node:lts-alpine as build-stage

# Work Directory
WORKDIR /app


# install and cache app dependencies
COPY package.json ./

RUN yarn install

COPY . .

# build app
RUN yarn build

#Production Environment
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
